"""Read and write the committed record of reviewed documents."""

from __future__ import annotations

import json
import re
from typing import TYPE_CHECKING

from docstale.errors import DocstaleError
from docstale.fsutil import atomic_write

if TYPE_CHECKING:
    from collections.abc import Mapping
    from pathlib import Path

LOCK_FILENAME = "docstale.lock"
_HEADER = "# Generated by `docstale stamp`. Commit this file with your changes.\n"
_ENTRY = re.compile(r'("(?:[^"\\]|\\.)*") = "([0-9a-f]{16})"')
# Git leaves these markers when a merge conflicts inside the file.
_CONFLICT_MARKERS = ("<<<<<<< ", "||||||| ", "=======", ">>>>>>> ")


class LockError(DocstaleError, ValueError):
    """Raised when the lock file cannot be read."""


def entry_line(document: str, fingerprint: str) -> str:
    """Return the line that records one document's fingerprint."""
    key = json.dumps(document, ensure_ascii=False).replace("\x7f", "\\u007f")
    return f'{key} = "{fingerprint}"'


def parse_lock(text: str) -> dict[str, str]:
    """Return recorded fingerprints, leaving out entries a merge left conflicting."""
    entries: dict[str, str] = {}
    conflicting: set[str] = set()
    for number, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if (
            not stripped
            or stripped.startswith("#")
            or stripped.startswith(_CONFLICT_MARKERS)
        ):
            continue
        match = _ENTRY.fullmatch(stripped)
        try:
            document = json.loads(match[1]) if match else None
        except json.JSONDecodeError:
            document = None
        if match is None or not isinstance(document, str):
            raise LockError(f"{LOCK_FILENAME} line {number} is not a lock entry")
        if entries.setdefault(document, match[2]) != match[2]:
            conflicting.add(document)
    return {
        document: fingerprint
        for document, fingerprint in entries.items()
        if document not in conflicting
    }


def render_lock(entries: Mapping[str, str]) -> str:
    """Render entries in path order, separated so that merges keep them apart."""
    lines = [_HEADER]
    lines.extend(
        f"\n{entry_line(document, fingerprint)}\n"
        for document, fingerprint in sorted(entries.items())
    )
    return "".join(lines)


def read_lock(path: Path) -> dict[str, str]:
    """Read recorded fingerprints, or none when the file does not exist."""
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return {}
    except UnicodeDecodeError as exc:
        raise LockError(f"{LOCK_FILENAME} is not UTF-8 text: {exc}") from exc
    return parse_lock(text)


def write_lock(path: Path, entries: Mapping[str, str]) -> None:
    """Replace the lock file with the given entries."""
    atomic_write(path, render_lock(entries))
