// Generated by doc-sync; managed-id: doc-sync.opencode.v1
type StructuredHookOutput = {
  status?: string;
  message?: string;
};

type SessionEvent = {
  type: string;
  properties?: {
    sessionID?: string;
  };
};

function getHookErrorMessage(
  stdout: string,
  stderr: string,
  exitCode: number,
): string {
  if (stdout) {
    try {
      const parsed = JSON.parse(stdout) as StructuredHookOutput;
      if (parsed.status === "review_required" && parsed.message) {
        return parsed.message;
      }
    } catch {
      return stdout;
    }
    return stdout;
  }
  if (stderr) return stderr;
  return `doc-sync hook failed with exit code ${exitCode}`;
}

export const DocSyncHook = async ({
  $,
  worktree,
}: {
  $: any;
  worktree: string;
}) => {
  return {
    event: async ({ event }: { event: SessionEvent }) => {
      if (event.type !== "session.idle") return;

      const sessionID = event.properties?.sessionID ?? `opencode:${worktree}`;
      const shell = $.cwd(worktree);
      // __DOC_SYNC_INVOCATION__

      if (result.exitCode !== 0) {
        throw new Error(
          getHookErrorMessage(
            result.text().trim(),
            result.stderr.toString().trim(),
            result.exitCode,
          ),
        );
      }
    },
  };
};
