from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from docstale.lock import (
    LockError,
    entry_line,
    parse_lock,
    read_lock,
    render_lock,
    write_lock,
)

if TYPE_CHECKING:
    from pathlib import Path

README = "1111111111111111"
API = "2222222222222222"
OTHER = "3333333333333333"


def test_renders_sorted_entries_separated_by_blank_lines() -> None:
    text = render_lock({"docs/api.md": API, "README.md": README})

    assert text.splitlines() == [
        "# Generated by `docstale stamp`. Commit this file with your changes.",
        "",
        f'"README.md" = "{README}"',
        "",
        f'"docs/api.md" = "{API}"',
    ]


def test_round_trips_unusual_document_paths(root: Path) -> None:
    entries = {'quote " and \\ slash.md': README, "ünïcode\x7f.md": API}
    path = root / "docstale.lock"

    write_lock(path, entries)

    assert read_lock(path) == entries
    assert "\x7f" not in path.read_text(encoding="utf-8")


def test_a_missing_lock_has_no_entries(root: Path) -> None:
    assert read_lock(root / "docstale.lock") == {}


def test_drops_entries_that_a_merge_left_conflicting() -> None:
    text = (
        f"<<<<<<< ours\n{entry_line('README.md', README)}\n"
        f"{entry_line('docs/new.md', API)}\n"
        f"=======\n{entry_line('README.md', OTHER)}\n"
        f"{entry_line('docs/other.md', OTHER)}\n>>>>>>> theirs\n"
    )

    assert parse_lock(text) == {"docs/new.md": API, "docs/other.md": OTHER}


def test_identical_entries_from_both_sides_are_kept() -> None:
    line = entry_line("README.md", README)

    assert parse_lock(f"{line}\n{line}\n") == {"README.md": README}


@pytest.mark.parametrize(
    "line",
    [
        "README.md = 1111111111111111",
        '"README.md" = "not-a-fingerprint"',
        '"bad \\q escape" = "1111111111111111"',
    ],
)
def test_rejects_lines_that_are_not_entries(line: str) -> None:
    with pytest.raises(LockError, match="line 1 is not a lock entry"):
        parse_lock(line)
